### ISSUE TITLE
Breaks in .gts files

### ISSUE THREAD

**Issue by vlascik** [ember-tooling/ember-eslint-parser#103]
```
> node_modules\.bin\eslint app\components\repro1.gts

TypeError: Cannot read properties of undefined (reading 'head')
	at preprocessGlimmerTemplates (P:\Project\node_modules\ember-eslint-parser\src\parser\transforms.js:323:27)
	at Object.parseForESLint (P:\Project\node_modules\ember-eslint-parser\src\parser\gjs-gts-parser.js:69:34)
	at Object.parse (P:\Project\node_modules\eslint\lib\languages\js\index.js:194:26)
	at ParserService.parseSync (P:\Project\node_modules\eslint\lib\services\parser-service.js:36:33)
	at #flatVerifyWithoutProcessors (P:\Project\node_modules\eslint\lib\linter\linter.js:1680:47)
	at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (P:\Project\node_modules\eslint\lib\linter\linter.js:1992:49)
	at P:\Project\node_modules\eslint\lib\linter\linter.js:1594:29
	at Array.map (<anonymous>)
	at Linter._verifyWithFlatConfigArrayAndProcessor (P:\Project\node_modules\eslint\lib\linter\linter.js:1589:36)
	at Linter._verifyWithFlatConfigArray (P:\Project\node_modules\eslint\lib\linter\linter.js:2068:25)
```

```ts
import Component from '@glimmer/component';

interface ReproSignature {
  Element: HTMLDivElement;
  Args: {
  };
  Blocks: {
    default: [];
  };
}

export default class ReproComponent extends Component<ReproSignature> {
  <template>
    <div id="1" class="repro" ...attributes>
    </div>
  </template>
}
```

Blows up on this code on line 323: 
https://github.com/ember-tooling/ember-eslint-parser/blob/257787c4975416b56955080b40aa4580445e3e98/src/parser/transforms.js#L321-L323

Seems that instead of setting `n.type` to `'Template'` the type is set to `'ElementNode'` with `n.tag` of `'template'`, and `n.path` is `undefined`.

I'm also having problems parsing even simple files like this with prettier (https://github.com/embroider-build/content-tag/issues/85), so maybe `content-tag` is involved? (Just a guess, as I have no idea how this tooling works).

**Comment by NullVoxPopuli** [comment]
can you provide the output of `pnpm why @glimmer/syntax` (or whatever the equiv is for your package manager)?

if you're pinning the version of `@glimmer/syntax`, that might be the problem.

**Comment by vlascik** [comment]
As commented on the other issue, even after pinning all the @glimmer packages to latest / 0.92.x, problem persists.

```
ember-eslint-parser@npm:0.5.3 [bdb64]
│  └─ @glimmer/syntax@npm:0.92.3 (via npm:0.92.3)
```

**Comment by NullVoxPopuli** [comment]
do you have a reproduction repo?

**Comment by vlascik** [comment]
So, after updating the syntax package, nuking node_modules and removing prettier from eslint config eslint works now.

Prettier still doesn't. Fun stuff.

I'm going to close this issue. Thank you.
